### ISSUE TITLE
LastFM: DB assigns based on hostmask break with Freenode gateway cloaks

### ISSUE THREAD

**Issue by cottongin** [GLolol/SupyPlugins#43]
When users set their Last FM user id, it assigns to current hostmask, this is nice, but.  With irccloud, and other webclients, that frequently change the user's hostmask, it appears to the end user to "forget" the association.

Example (all same irc user and Last FM user):
- `'<user 1>@gateway/web/cgi-irc/kiwiirc.com/ip.###.###.###.###: <lastfm user 1>'`
- `'<user 1>@gateway/web/irccloud.com/x-abcdefghijklmnop: <lastfm user 1>'`
- `'<user 1>@gateway/web/irccloud.com/x-bcdefghijklmnopq: <lastfm user 1>'`
- `'<user 1>@gateway/web/irccloud.com/x-cdefghijklmnopqr: <lastfm user 1>'`

**Comment by GLolol** [comment]
Grr, this isn't really irccloud's fault but rather freenode's. I'm not sure how the `x-abcdefghijklmnop` part of gateway cloaks are generated - are they related to the user's connection info at all, or just randomly generated?

A possible solution could be to save LastFM IDs to registered bot accounts first, and then look only at people's hostmasks if they're not logged in to the bot. Any thoughts?

**Comment by cottongin** [comment]
Yeah, I'm not sure what the ideal solution is here either.  I too do not know what freenode's (or any other network's) policy is regarding generation of hostmasks for webclient/irccloud users.  According to https://www.irccloud.com/abuse:

- Each IRCCloud user is allocated a unique, static user ID which they cannot change.
- This ID is included in the username and is verified by IDENT, so it can be used to positively identify one user for banning.

One solution could be to assign based on the static user ID, but I believe this would only work for irccloud users and isn't ideal.

The idea to save based on registered bot users is good too, but would require users to register with the bot, and at least in my case, that is a minority of users.

**Comment by cottongin** [comment]
Additional information specific to Freenode:
https://blog.freenode.net/2010/06/freenode-webchat-changes/

> **The unique connection string changes every time a user makes a new connection** through webchat. Therefore, we’ve changed how we do the cloaking so IPs are shown in cloaks. This makes it much simpler for channel staff to see what is going on, and who is who. For now, this change only applies to those using the freenode webchat at http://webchat.freenode.net. The effect is to change a cloak of the form “gateway/web/freenode/**x-iiqzrxiqfnnglqji**” to the form “gateway/web/freenode/ip.171.205.239.16“.

**Comment by GLolol** [comment]
I know that IRCCloud uses idents based on the UID, but freenode..really? That's a stupid system. :/
