### ISSUE TITLE
Replacer: does not recognize non-slash delimiters

### ISSUE THREAD

**Issue by jztech101** [GLolol/SupyPlugins#50]
Any character can be used in place of / in s/x/y/ as long as all three of them match.

**Comment by t3chguy** [comment]
That is intentional @jztech101 it was a choice I made when I wrote it. A lot of regex implementations allow you to use a few different symbols, in my implementation you can use pretty much any. (I wrote the plugin before @GLolol forked it - my version has the same functionality)

**Comment by t3chguy** [comment]
@GLolol I think your new title is inversely linked to the orginal

**Comment by t3chguy** [comment]
Looks like @GLolol's changes remove the original behaviour which can be found here.https://github.com/t3chguy/Limnoria-Plugins/blob/master/Replacer/plugin.py

**Comment by GLolol** [comment]
Python doesn't even have a sed-style regex implementation. `unpack_sed` is a hack, plain and simple.

**Comment by GLolol** [comment]
I was not aware that sed officially supported other symbols before today.

**Comment by jztech101** [comment]
What? "In my implementation you can use pretty much any" Vs. "This is
intentional, it was a choice I made when I wrote it"

**Comment by t3chguy** [comment]
@jztech101 see my link in the comment 20 hours ago for the original plugin Repo, @GLolol's does not have non-slash support, mine (original) does.

**Comment by jztech101** [comment]
Ah ok. Sorry, missed it.
