### ISSUE TITLE
RelayNext: Use a zero-width space for the "noHighlight" feature

### ISSUE THREAD

**Issue by Zoddo** [GLolol/SupyPlugins#55]
Adding a ZWS after the first character of the nick should works in more client than the hyphen.

**Comment by Zoddo** [comment]
Fixed by GH-57

**Comment by GLolol** [comment]
..and 436956cb998bc77292beb93fe84fad488849aad7 and 546851574e6c2ed68236cf8d6603eabd94bfd42f ;)
