### ISSUE TITLE
SedRegex: handle regex termination properly

### ISSUE THREAD

**Issue by nyuszika7h** [GLolol/SupyPlugins#59]
```
13:11:12 <nyu> good thing they support PayPal
13:11:18 <nyu> so if it doesn't work out I can ask for a refund
13:11:33 <nyu> s/support/use/ don't even have another method
13:11:33 <@Caroline> nyu meant to say: good thing they use/ don't even have another method PayPal
```

The regex is the terminated with the `/` after `use`, but the plugin ignores that and just matches the rest of the line too.

**Comment by GLolol** [comment]
Hmm, I had it this way so that the plugin would still work if people forget the trailing /, but it seems that has other side effects.
