### ISSUE TITLE
Error: Connection timed out.

### ISSUE THREAD

**Issue by usenethound** [GLolol/SupyPlugins#61]
First of all, thanks for the plugin!

The weather plugin has been throwing a bunch of Error: Connection timed out. errors for weeks now. The plugin does work on occasion for me though. All I could find online is that WU moved some things over to AWS sometime after the New Year and it is a little more touchy with server requests.

Thanks

**Comment by GLolol** [comment]
This looks like a network issue, because the plugin works fine for me and in [testing](https://travis-ci.org/GLolol/SupyPlugins/jobs/213516353). It looks like Wunderground is using akamai for their hosting though, so maybe check if you can resolve and access these hosts:

```
gl@millennium:~$ dns autocomplete.wunderground.com
autocomplete.wunderground.com is an alias for autocomplete-wxu.weather-perf.akadns.net.
autocomplete-wxu.weather-perf.akadns.net has address 50.112.148.189
autocomplete-wxu.weather-perf.akadns.net has address 54.213.230.209
autocomplete-wxu.weather-perf.akadns.net has address 54.69.227.47
```
```
gl@millennium:~$ dns api.wunderground.com
api.wunderground.com is an alias for api.wunderground.com.edgekey.net.
api.wunderground.com.edgekey.net is an alias for e2040.g.akamaiedge.net.
e2040.g.akamaiedge.net has address 104.92.115.119
```

**Comment by usenethound** [comment]
root@meme:/home/usenethound# host autocomplete.wunderground.com
autocomplete.wunderground.com is an alias for autocomplete-wxu.weather-perf.akadns.net.
autocomplete-wxu.weather-perf.akadns.net has address 50.112.148.189
autocomplete-wxu.weather-perf.akadns.net has address 54.213.230.209
autocomplete-wxu.weather-perf.akadns.net has address 54.69.227.47
root@meme:/home/usenethound# host api.wunderground.com
api.wunderground.com is an alias for api.wunderground.com.edgekey.net.
api.wunderground.com.edgekey.net is an alias for e2040.g.akamaiedge.net.
e2040.g.akamaiedge.net has address 104.118.220.169

**Comment by GLolol** [comment]
Do you have an API key and everything else set up?

**Comment by usenethound** [comment]
Yep, and like I said sometimes it works flawless and other times it hangs for awhile without a response and times out. This one has me stumped for sure :/

**Comment by usenethound** [comment]
Just to add, I have been using this plugin for years.

Right now it seems to be working, but I'm getting delays of about almost 1 minute before I get a response back from the WU API

**Comment by GLolol** [comment]
That's likely a network issue. What ISP and location are you trying to reach WU from? What are the ping times to `api.wunderground.com`? Are you getting lag to other sites as well?

**Comment by usenethound** [comment]
The bot is running on hostus.us on a VPS in the Atlanta Datacenter

Now that you mention it I have noticed some odd disconnections on my ZNC client to a few IRC networks around the same time this started happening.

`PING e2040.g.akamaiedge.net (104.118.220.169) 56(84) bytes of data.
64 bytes from a104-118-220-169.deploy.static.akamaitechnologies.com (104.118.220.169): icmp_seq=1 ttl=55 time=16.0 ms
64 bytes from a104-118-220-169.deploy.static.akamaitechnologies.com (104.118.220.169): icmp_seq=2 ttl=55 time=16.0 ms
64 bytes from a104-118-220-169.deploy.static.akamaitechnologies.com (104.118.220.169): icmp_seq=3 ttl=55 time=15.9 ms
64 bytes from a104-118-220-169.deploy.static.akamaitechnologies.com (104.118.220.169): icmp_seq=4 ttl=55 time=15.9 ms
64 bytes from a104-118-220-169.deploy.static.akamaitechnologies.com (104.118.220.169): icmp_seq=5 ttl=55 time=15.9 ms
64 bytes from a104-118-220-169.deploy.static.akamaitechnologies.com (104.118.220.169): icmp_seq=6 ttl=55 time=15.9 ms
64 bytes from a104-118-220-169.deploy.static.akamaitechnologies.com (104.118.220.169): icmp_seq=7 ttl=55 time=15.9 ms
64 bytes from a104-118-220-169.deploy.static.akamaitechnologies.com (104.118.220.169): icmp_seq=8 ttl=55 time=15.9 ms
64 bytes from a104-118-220-169.deploy.static.akamaitechnologies.com (104.118.220.169): icmp_seq=9 ttl=55 time=15.9 ms
64 bytes from a104-118-220-169.deploy.static.akamaitechnologies.com (104.118.220.169): icmp_seq=10 ttl=55 time=15.9 ms
`

`traceroute to api.wunderground.com (104.118.220.169), 30 hops max, 60 byte packets
 1  * * *
 2  192.168.250.253 (192.168.250.253)  12.103 ms  12.198 ms  12.537 ms
 3  te0-0-2-1.nr11.b007549-1.atl01.atlas.cogentco.com (38.88.10.253)  16.207 ms  16.228 ms  16.302 ms
 4  te0-2-0-0.agr21.atl01.atlas.cogentco.com (154.24.49.137)  16.227 ms  16.249 ms  16.280 ms
 5  te0-18-0-2.ccr41.atl01.atlas.cogentco.com (154.54.47.189)  15.866 ms te0-18-0-2.ccr42.atl01.atlas.cogentco.com (154.54.47.197)  18.612 ms te0-1-0-17.ccr41.atl01.atlas.cogentco.com (154.54.30.93)  18.863 ms
 6  be2848.ccr41.atl04.atlas.cogentco.com (154.54.6.118)  18.952 ms be2847.ccr41.atl04.atlas.cogentco.com (154.54.6.102)  18.476 ms be2848.ccr41.atl04.atlas.cogentco.com (154.54.6.118)  18.466 ms
 7  a104-118-220-169.deploy.static.akamaitechnologies.com (104.118.220.169)  16.172 ms  15.958 ms  16.192 ms
`

**Comment by GLolol** [comment]
You should open a ticket with your server provider since there's nothing I can do at the network level. Best of luck on getting things fixed :)
